### ISSUE TITLE
Failed to sign a reveal

### ISSUE THREAD

**Issue by spalmer25** [trilitech/ledger-app-tezos-baking#11]
The signature of a reveal operation seems authorised but fails.

**Comment by spalmer25** [comment]
Investigation:
In [apdu_sign](https://github.com/trilitech/ledger-app-tezos-baking/blob/main/src/apdu_sign.c#L168), there is a condition that checks that the `destination` is the same as the authorised key.
This makes sense for `delegation`, but `reveal` has no `destination` (but a public key).

A [comment](https://github.com/trilitech/ledger-app-tezos-baking/blob/main/src/operations.c#L495-L498) in `operations.c` indicates that reveal isn't that dangerous.
Do we want to check the `public_key` of `reveal` instead of the `destination`?

**Comment by spalmer25** [comment]
On the other hand, it is possible to sign a `reveal` if it is in an operation batch than a `delegation`.

**Comment by emturner** [comment]
I think it would be good to assert that `pk of reveal == authorized key`, and fail otherwise
