### ISSUE TITLE
Fix screensaver behavior

### ISSUE THREAD

**Issue by ajinkyaraj-23** [trilitech/ledger-app-tezos-baking#21]
- [x] #45
- [ ] Stax screensaver needs to be fixed.

**Comment by spalmer25** [comment]
## Screen saver behaviour:
 - If the screen saver is not already activate, it will be activated when sign a baking operation (no matter user navigation).
 - The pin code is asked to exit screen saver.
 - (Nice to have) Allow to set manually the screen saver.

**Comment by ajinkyaraj-23** [comment]
As we are using ledger io event timer, screensaver operation will be handled by ledger SDK including stax. Threfore we can close this issue.
