### ISSUE TITLE
Duplicate files with ledger-secure-sdk

### ISSUE THREAD

**Issue by ajinkyaraj-23** [trilitech/ledger-app-tezos-baking#32]
Following warning while compiling with updated ledger SDK
`[WARNING] Found duplicate files in SDK and APP: base58.h swap_lib_calls.h swap_utils.h`
Rename app files so that duplication is avoided.

**Comment by spalmer25** [comment]
It's probably worth checking if we can use Ledger's `base58.h`, `swap_lib_calls.h` and `swap_utils.h` instead.

**Comment by ajinkyaraj-23** [comment]
Working on it.
